In [48]:
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from pathlib import Path
import pandas as pd

In [42]:
base_path = Path("..")
train_path = base_path/"data"/"raw"/"train.csv"
test_path = base_path/"data"/"raw"/"test.csv"

In [43]:
train_df = pl.read_csv(train_path)
print(train_df.head())
print(train_df.shape)
print(train_df.schema)
train_df.columns

shape: (5, 15)
┌─────┬─────┬─────────────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ id  ┆ Age ┆ Annual_Inco ┆ Daily_Commu ┆ … ┆ Home_Chargi ┆ Subsidy_Ava ┆ Range_Anxie ┆ Will_Buy_E │
│ --- ┆ --- ┆ me_USD      ┆ te_km       ┆   ┆ ng_Possible ┆ ilable      ┆ ty_Level    ┆ V          │
│ i64 ┆ i64 ┆ ---         ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---        │
│     ┆     ┆ f64         ┆ f64         ┆   ┆ str         ┆ str         ┆ str         ┆ str        │
╞═════╪═════╪═════════════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ 0   ┆ 66  ┆ 92887.0     ┆ 23.4        ┆ … ┆ Yes         ┆ No          ┆ Low         ┆ No         │
│ 1   ┆ 38  ┆ 30000.0     ┆ 5.0         ┆ … ┆ Yes         ┆ No          ┆ Low         ┆ No         │
│ 2   ┆ 26  ┆ 94389.0     ┆ 36.8        ┆ … ┆ No          ┆ Yes         ┆ Low         ┆ Yes        │
│ 3   ┆ 66  ┆ 73580.0     ┆ 23.7        ┆ … ┆ Yes         ┆ No          ┆ Low         ┆ No         │
│ 4   ┆ 54  ┆ 57898.0     ┆ 50.8        ┆ … ┆ Yes         ┆ No          ┆ Low         ┆ No         │
└─────┴─────┴─────────────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴────────────┘
(668665, 15)
Schema({'id': Int64, 'Age': Int64, 'Annual_Income_USD': Float64, 'Daily_Commute_km': Float64, 'Number_of_Cars_Owned': Int64, 'Charging_Stations_Near_Home': Int64, 'Charging_Stations_Near_Work': Int64, 'Environmental_Concern_Level': Float64, 'Gender': String, 'City_Type': String, 'Current_Car_Type': String, 'Home_Charging_Possible': String, 'Subsidy_Available': String, 'Range_Anxiety_Level': String, 'Will_Buy_EV': String})

['id',
 'Age',
 'Annual_Income_USD',
 'Daily_Commute_km',
 'Number_of_Cars_Owned',
 'Charging_Stations_Near_Home',
 'Charging_Stations_Near_Work',
 'Environmental_Concern_Level',
 'Gender',
 'City_Type',
 'Current_Car_Type',
 'Home_Charging_Possible',
 'Subsidy_Available',
 'Range_Anxiety_Level',
 'Will_Buy_EV']

In [44]:
train_df.describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ id        ┆ Age       ┆ Annual_In ┆ … ┆ Home_Char ┆ Subsidy_A ┆ Range_Anx ┆ Will_Buy │
│ ---       ┆ ---       ┆ ---       ┆ come_USD  ┆   ┆ ging_Poss ┆ vailable  ┆ iety_Leve ┆ _EV      │
│ str       ┆ f64       ┆ f64       ┆ ---       ┆   ┆ ible      ┆ ---       ┆ l         ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆ ---       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 668665.0  ┆ 668665.0  ┆ 668665.0  ┆ … ┆ 668665    ┆ 668665    ┆ 668665    ┆ 668665   │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 334332.0  ┆ 47.039171 ┆ 84769.266 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 989       ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 193027.10 ┆ 12.875448 ┆ 28648.029 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 3211      ┆           ┆ 042       ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 0.0       ┆ 25.0      ┆ 30000.0   ┆ … ┆ No        ┆ No        ┆ High      ┆ No       │
│ 25%       ┆ 167166.0  ┆ 36.0      ┆ 67376.0   ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 50%       ┆ 334332.0  ┆ 47.0      ┆ 84880.0   ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 75%       ┆ 501498.0  ┆ 58.0      ┆ 102753.0  ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ max       ┆ 668664.0  ┆ 69.0      ┆ 188549.0  ┆ … ┆ Yes       ┆ Yes       ┆ Medium    ┆ Yes      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [45]:
train_df.null_count()

shape: (1, 15)
┌─────┬─────┬─────────────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ id  ┆ Age ┆ Annual_Inco ┆ Daily_Commu ┆ … ┆ Home_Chargi ┆ Subsidy_Ava ┆ Range_Anxie ┆ Will_Buy_E │
│ --- ┆ --- ┆ me_USD      ┆ te_km       ┆   ┆ ng_Possible ┆ ilable      ┆ ty_Level    ┆ V          │
│ u32 ┆ u32 ┆ ---         ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---        │
│     ┆     ┆ u32         ┆ u32         ┆   ┆ u32         ┆ u32         ┆ u32         ┆ u32        │
╞═════╪═════╪═════════════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ 0   ┆ 0   ┆ 0           ┆ 0           ┆ … ┆ 0           ┆ 0           ┆ 0           ┆ 0          │
└─────┴─────┴─────────────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [46]:
train_df["Will_Buy_EV"].value_counts()
552886 / (552886 + 116779)

0.8256157929711124

#### Disbalance
Classes have significant disbalance (if the model determines all the points as the class "NO", then accuracy will be about 82.5%)
Then the best way is to use other metrics

In [ ]:
numeric_features = [
    "Age",
    "Annual_Income_USD",
    "Daily_Commute_km",
    "Number_of_Cars_Owned",
    "Charging_Stations_Near_Home",
    "Charging_Stations_Near_Work",
    "Environmental_Concern_Level",
    "Range_Anxiety_Level"
]

categorical_features = [
    "Gender",
    "City_Type",
    "Current_Car_Type",
    "Home_Charging_Possible",
    "Subsidy_Available"
]

In [ ]:
target = train_df["Will_Buy_EV"]
plt.scatter(
    df["area"].to_numpy(),
    target.to_numpy(),
    alpha=0.5
)

plt.xlabel("Area")
plt.ylabel("Price")
plt.show()

['id',
 'Age',
 'Annual_Income_USD',
 'Daily_Commute_km',
 'Number_of_Cars_Owned',
 'Charging_Stations_Near_Home',
 'Charging_Stations_Near_Work',
 'Environmental_Concern_Level',
 'Gender',
 'City_Type',
 'Current_Car_Type',
 'Home_Charging_Possible',
 'Subsidy_Available',
 'Range_Anxiety_Level',
 'Will_Buy_EV']